#!/bin/bash
/pi/install samba
/pi/install buttons
/pi/install led

/do/ledsButtons/scripts/samba/remove
/do/ledsButtons/scripts/ssh/remove

/do/ledsButtons/scripts/ssh/add
/do/ledsButtons/scripts/samba/add

cp /do/ledsButtons/config/security.cfg /user/config/buttons/buttons.cfg
/do/buttons/restart
