#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [gpio] [buttons] [electronics] [pull-up]"
	/show/usageDescription "Check state of button on pin 26"
	/show/usage "$0"
	/show/return "0 : not press -- 1 : press"
	exit 1
else
  /do/buttons/state 26
fi
