#!/bin/bash
echo -ne $ERR

/do/2b3l/logoGreen

/do/2b3l/pinOut

/pi/install led
/pi/install buttons
/pi/install supervisor


/do/2b3l/logoRed

/show/listecho "Test : /do/2b3l/test" $OK
/show/listecho "Setup : /do/2b3l/setup" $WARN
/show/listecho "Security Mode : /do/2b3l/security" $ERR
