#!/bin/bash
/pi/install samba

/do/2b3l/scripts/samba/remove
/do/2b3l/scripts/ssh/remove

/do/2b3l/scripts/ssh/add
/do/2b3l/scripts/samba/add

cp /do/2b3l/config/security.cfg /user/config/buttons/buttons.cfg
/do/buttons/restart
