#!/bin/bash
redState=$(/do/2b3l/redState)
greenState=$(/do/2b3l/greenState)
yellowState=$(/do/2b3l/yellowState)
button1State=$(/do/2b3l/button1State)
button2State=$(/do/2b3l/button2State)
echo "red:$redState;yellow:$yellowState;green:$greenState;button1:$button1State;button2:$button2State"
