#!/bin/bash
/do/2b3l/logoRed
cp /do/2b3l/config/leds.cfg /user/config/buttons/buttons.cfg
/show/file /user/config/buttons/buttons.cfg
/do/buttons/restart
/do/2b3l/logoGreen
/show/listecho "Button 1 to turn leds ON" $OK
/show/listecho "Button 2 to turn leds OFF" $ERR
