#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [gpio] [led] [electronics]"
	/show/usageDescription "Turn on yellow led (pin 20)"
	/show/usage "$0"
	exit 1
else
  /do/led/on 20
fi
